### PR TITLE
Adds GameUiMessageMp references to GameUiMp interface

### PR DESCRIPTION
**Pull request by n0minal**

### CODE REVIEW

**Comment by CocaColaBear** [comment]
Hm. What it is?

**Comment by CocaColaBear** [comment]
The are no such types in RageMP

**Comment by n0minal** [comment]
Ofcourse there is, just look at wiki and you'll see about entity setAlpha params and take a look here about Scaleform messages: https://rage.mp/files/file/26-scaleform-messages/, RAGEMP wiki bot is broken.

**Comment by CocaColaBear** [comment]
@n0minal yea, setAlpha is fixed, thanks.
If you want to use methods from custom package (for example, scaleform-messages), create _**d.ts**_ file in your project and merge interface from typings. 
See: https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by n0minal** [comment]
Sorry, I didn't notice it was a custom function (I was really really sleepy).

**Pull request closed without merging**
